site_name: DSViz
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: guide.md
  - Documentation:
    - Package Structure: structure.md
    - ArrayListV: array.md
    - LinkedListV: list.md
    - BinaryTreeV: binaryTree.md
    - GraphV: graph.md
  - Examples: 
    - Binary Search Tree Example: BSTExample.md
    - Undirected Graph: undirected_graph.md
    - Directed Graph: directed_graph.md
  - License: license.md

theme: 
  logo: Capture5.png
  favicon: Capture5.png
  features:
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.instant
    
  name: material #pip install mkdocs-material
  icon:
    repo: fontawesome/brands/github
  palette:

    - scheme: default

      toggle:

        icon: material/toggle-switch-off-outline

        name: Switch to dark mode
    - scheme: slate

      toggle:

        icon: material/toggle-switch

        name: Switch to light mode
  
repo_url: https://github.com/IshMehta/DSViz
repo_name: IshMehta/DSViz

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/IshMehta/DSViz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ish-mehta-529766166

copyright: Copyright &copy; 2021 Ish Mehta

use_pygments: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
